In [1]:
!pip install emoji

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting emoji
  Downloading emoji-2.1.0.tar.gz (216 kB)
     |████████████████████████████████| 216 kB 30.9 MB/s
Building wheels for collected packages: emoji
  Building wheel for emoji (setup.py) ... done
  Created wheel for emoji: filename=emoji-2.1.0-py3-none-any.whl size=212392 sha256=854b8432b9aa23d0006426867195d3a804909aa184ce4aba330dba8e9c3f0ad9
  Stored in directory: /root/.cache/pip/wheels/77/75/99/51c2a119f4cfd3af7b49cc57e4f737bed7e40b348a85d82804
Successfully built emoji
Installing collected packages: emoji
Successfully installed emoji-2.1.0

In [2]:
import pandas as pd
import numpy as np
import emoji

In [3]:
dicionario = {'Laura':np.random.uniform(6,10,5).round(1),
              'Elienai':np.random.uniform(3,10,5).round(1),
              'Miriam':np.random.uniform(3,10,5).round(1),
              'Giovana':np.random.uniform(3,10,5).round(1),
              'Bianca':np.random.uniform(3,10,5).round(1),
              'Esther':np.random.uniform(3,10,5).round(1),
              'Neide':np.random.uniform(3,10,5).round(1),
              'Ana':np.random.uniform(3,10,5).round(1)}

In [4]:
provas = pd.DataFrame(dicionario)

In [6]:
provas

   Laura  Elienai  Miriam  Giovana  Bianca  Esther  Neide  Ana
0   10.0      9.1     9.8      5.5     8.4     9.2    7.9  7.6
1    7.9      9.8     9.0      9.2     5.2     8.0    7.7  9.0
2    8.7      4.6     7.2      9.0     8.5     7.6    9.0  7.5
3    6.4      6.4     3.3      4.9     6.8     3.9    5.9  6.2
4    8.4      6.2     8.9      6.9     9.3     3.3    8.0  7.7

In [7]:
provas.index = ['Portugues', 'Matematica', 'Geografia', 'Ciencias', 'Ingles']

In [8]:
provas

            Laura  Elienai  Miriam  Giovana  Bianca  Esther  Neide  Ana
Portugues    10.0      9.1     9.8      5.5     8.4     9.2    7.9  7.6
Matematica    7.9      9.8     9.0      9.2     5.2     8.0    7.7  9.0
Geografia     8.7      4.6     7.2      9.0     8.5     7.6    9.0  7.5
Ciencias      6.4      6.4     3.3      4.9     6.8     3.9    5.9  6.2
Ingles        8.4      6.2     8.9      6.9     9.3     3.3    8.0  7.7

In [9]:
provas = provas.T

In [10]:
provas

         Portugues  Matematica  Geografia  Ciencias  Ingles
Laura         10.0         7.9        8.7       6.4     8.4
Elienai        9.1         9.8        4.6       6.4     6.2
Miriam         9.8         9.0        7.2       3.3     8.9
Giovana        5.5         9.2        9.0       4.9     6.9
Bianca         8.4         5.2        8.5       6.8     9.3
Esther         9.2         8.0        7.6       3.9     3.3
Neide          7.9         7.7        9.0       5.9     8.0
Ana            7.6         9.0        7.5       6.2     7.7

In [11]:
provas['Nota_Minima'] = provas.min(axis=1).round(1)
provas['Nota_Media'] = provas.mean(axis=1).round(1)
provas['Nota_Maxima'] = provas.max(axis=1).round(1)

In [12]:
provas

,Portugues,Matematica,Geografia,Ciencias,Ingles,Nota_Minima,Nota_Media,Nota_Maxima
Laura,10.0,7.9,8.7,6.4,8.4,6.4,8.0,10.0
Elienai,9.1,9.8,4.6,6.4,6.2,4.6,6.8,9.8
Miriam,9.8,9.0,7.2,3.3,8.9,3.3,6.9,9.8
Giovana,5.5,9.2,9.0,4.9,6.9,4.9,6.7,9.2
Bianca,8.4,5.2,8.5,6.8,9.3,5.2,7.2,9.3
Esther,9.2,8.0,7.6,3.9,3.3,3.3,5.9,9.2
Neide,7.9,7.7,9.0,5.9,8.0,5.9,7.4,9.0
Ana,7.6,9.0,7.5,6.2,7.7,6.2,7.4,9.0

In [13]:
def aux(x):
  if x >= 6:
    return 'Aprovado'
  elif x >= 4 and x < 6:
    return 'Recuperação'
  else:
    return 'Reprovado'

provas['Situação_da_Aluna'] = provas['Nota_Media'].apply(aux)

In [14]:
provas

,Portugues,Matematica,Geografia,Ciencias,Ingles,Nota_Minima,Nota_Media,Nota_Maxima,Situação_da_Aluna
Laura,10.0,7.9,8.7,6.4,8.4,6.4,8.0,10.0,Aprovado
Elienai,9.1,9.8,4.6,6.4,6.2,4.6,6.8,9.8,Aprovado
Miriam,9.8,9.0,7.2,3.3,8.9,3.3,6.9,9.8,Aprovado
Giovana,5.5,9.2,9.0,4.9,6.9,4.9,6.7,9.2,Aprovado
Bianca,8.4,5.2,8.5,6.8,9.3,5.2,7.2,9.3,Aprovado
Esther,9.2,8.0,7.6,3.9,3.3,3.3,5.9,9.2,Recuperação
Neide,7.9,7.7,9.0,5.9,8.0,5.9,7.4,9.0,Aprovado
Ana,7.6,9.0,7.5,6.2,7.7,6.2,7.4,9.0,Aprovado

In [15]:
def aux_2(xx):
  if xx >= 6:
    return '\U0001F600''\U0001F7E9'
  elif xx >= 4 and xx < 6:
    return '\U0001F620''\U0001F7E8'
  else:
    return '\U0001F630''\U0001F7E5'

provas['Humor'] = provas['Nota_Media'].apply(aux_2)

In [16]:
provas

,Portugues,Matematica,Geografia,Ciencias,Ingles,Nota_Minima,Nota_Media,Nota_Maxima,Situação_da_Aluna,Humor
Laura,10.0,7.9,8.7,6.4,8.4,6.4,8.0,10.0,Aprovado,😀🟩
Elienai,9.1,9.8,4.6,6.4,6.2,4.6,6.8,9.8,Aprovado,😀🟩
Miriam,9.8,9.0,7.2,3.3,8.9,3.3,6.9,9.8,Aprovado,😀🟩
Giovana,5.5,9.2,9.0,4.9,6.9,4.9,6.7,9.2,Aprovado,😀🟩
Bianca,8.4,5.2,8.5,6.8,9.3,5.2,7.2,9.3,Aprovado,😀🟩
Esther,9.2,8.0,7.6,3.9,3.3,3.3,5.9,9.2,Recuperação,😠🟨
Neide,7.9,7.7,9.0,5.9,8.0,5.9,7.4,9.0,Aprovado,😀🟩
Ana,7.6,9.0,7.5,6.2,7.7,6.2,7.4,9.0,Aprovado,😀🟩

In [17]:
provas = provas.sort_values('Nota_Media', ascending=False)

In [18]:
provas

,Portugues,Matematica,Geografia,Ciencias,Ingles,Nota_Minima,Nota_Media,Nota_Maxima,Situação_da_Aluna,Humor
Laura,10.0,7.9,8.7,6.4,8.4,6.4,8.0,10.0,Aprovado,😀🟩
Neide,7.9,7.7,9.0,5.9,8.0,5.9,7.4,9.0,Aprovado,😀🟩
Ana,7.6,9.0,7.5,6.2,7.7,6.2,7.4,9.0,Aprovado,😀🟩
Bianca,8.4,5.2,8.5,6.8,9.3,5.2,7.2,9.3,Aprovado,😀🟩
Miriam,9.8,9.0,7.2,3.3,8.9,3.3,6.9,9.8,Aprovado,😀🟩
Elienai,9.1,9.8,4.6,6.4,6.2,4.6,6.8,9.8,Aprovado,😀🟩
Giovana,5.5,9.2,9.0,4.9,6.9,4.9,6.7,9.2,Aprovado,😀🟩
Esther,9.2,8.0,7.6,3.9,3.3,3.3,5.9,9.2,Recuperação,😠🟨

In [19]:
provas[provas['Nota_Media'] >= 6]

,Portugues,Matematica,Geografia,Ciencias,Ingles,Nota_Minima,Nota_Media,Nota_Maxima,Situação_da_Aluna,Humor
Laura,10.0,7.9,8.7,6.4,8.4,6.4,8.0,10.0,Aprovado,😀🟩
Neide,7.9,7.7,9.0,5.9,8.0,5.9,7.4,9.0,Aprovado,😀🟩
Ana,7.6,9.0,7.5,6.2,7.7,6.2,7.4,9.0,Aprovado,😀🟩
Bianca,8.4,5.2,8.5,6.8,9.3,5.2,7.2,9.3,Aprovado,😀🟩
Miriam,9.8,9.0,7.2,3.3,8.9,3.3,6.9,9.8,Aprovado,😀🟩
Elienai,9.1,9.8,4.6,6.4,6.2,4.6,6.8,9.8,Aprovado,😀🟩
Giovana,5.5,9.2,9.0,4.9,6.9,4.9,6.7,9.2,Aprovado,😀🟩

In [20]:
provas[provas['Nota_Media'] < 6]

,Portugues,Matematica,Geografia,Ciencias,Ingles,Nota_Minima,Nota_Media,Nota_Maxima,Situação_da_Aluna,Humor
Esther,9.2,8.0,7.6,3.9,3.3,3.3,5.9,9.2,Recuperação,😠🟨